### ISSUE TITLE
Support cycles bigger than 2

### ISSUE THREAD

**Issue by sk-havok** [dschwen/switch-header-source#10]
For example, some projects have headers (.h) inline (.inl) and source (.cpp)
Or one could imagine foo.py, foo.html, foo.css

I suggest removing the distinction of header/source in the settings.
Just have one big regex. It finds the current position and tries each subsequent one in turn (wrapping round)

So one might have .h|.hxx|.inl|.cpp|.cxx

**Comment by dschwen** [comment]
Working in this right now. Initial version in fbb77db
