### ISSUE TITLE
Can't find header when it is not in the same folder

### ISSUE THREAD

**Issue by Aukstkalnis** [dschwen/switch-header-source#11]
My root project has header folder and source folder. Switch is not working for me.

**Comment by dschwen** [comment]
Can you give me an example for a corresponding path pair?

**Comment by alexxx537** [comment]
Sure:)
#My_project
       #HeadersFolder
              #Folder1
                     S1.h
              #Folder2
                     S2.h
              S3.h
       #SourceFolder
              #Folder1
                     S1.c
              #Folder2
                     S2.c
              S3.c
That's how my project look. However, header file can be placed in different folder than source. I think the best way to do this would be to just search entire root folder for headers and sources.

**Comment by schultzern** [comment]
Same here. I have code .cc files in one folder and .h files in inc or include folders, e.g.

# my_project
-----# my_code.cc
-----# inc
----------# my_code.h

Switch is not working on Linux, CentOS.

**Comment by TDHolmes** [comment]
I'm also seeing this issue with the following structure:

- Project
  - Inc
    - header_1.h
  - Src
    - source_1.c

I am on MacOS

**Comment by maxshaffer** [comment]
I'm seeing the same problem as everyone else. I have the same folder structure as above.

**Comment by dschwen** [comment]
@TDHolmes the header and source files should have the same base name. `header_1.h` and `source_1.c` cannot be matched. Or is your actual project different?

**Comment by maxshaffer** [comment]
I think @TDHolmes meant the files are named 'somename.h' and 'somename.c'.

**Comment by Aukstkalnis** [comment]
I think that all C/C++ developers uses microsoft C/C++ extension and that extension already has this feature that works well.

**Comment by dschwen** [comment]
@Aukstkalnis, which plugin is that?

**Comment by Aukstkalnis** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by dschwen** [comment]
Wait... am I missing something here? That is not an Atom plugin.

**Comment by Aukstkalnis** [comment]
Yes, you right... Wrong editor... Sorry😅

**Comment by dschwen** [comment]
Ok, I'm working on a new release that will use the fuzzy finder code to do indexing and more flexible switching.
