### ISSUE TITLE
Option to switch within the same tab

### ISSUE THREAD

**Issue by SEbbaDK** [dschwen/switch-header-source#15]
When i enable the same pane switcher, a permanent pane is opened for the .h file instead of using the current pane.

**Comment by dschwen** [comment]
Hm, that seems to be a new one. Are you on 1.23.0?

**Comment by dschwen** [comment]
I cannot reproduce this in 1.23.0. Can you give me a few more details? I.e. which files are open (h and/or c?), how many open panes do you have, which file is in which pane? What happens if you trigger switch-header-source the first time, what happens if you trigger it the second time?

**Comment by SEbbaDK** [comment]
Sorry, i was understanding pane as tab, and thought it would change the current tab to show the other file.
I was at 1.23.0

**Comment by dschwen** [comment]
Oh, yeah, I don't have an in-tab switching. Is this a requested feature? What would I do with unsaved changes when switching? I guess I could look at the _pending_ tab state (when the tab title is italic) and allow in tab switching for pending tabs (as long as their content is unchanged).

**Comment by SEbbaDK** [comment]
Same tab switching would be optimal for me, since my header files are usually so small and i only edit them when touching the .c file too

**Comment by dschwen** [comment]
This is actually in 0.27.0, just enable the "New tab pending" option and it will switch the pending tab to a new pending tab in place.
