### ISSUE TITLE
Doc on howto add a new couple of switches

### ISSUE THREAD

**Issue by bguil** [dschwen/switch-header-source#18]
#17 is fixed in 0.24.4, thanks.

I use the package for Ocaml editing and so I need to switch between `<file>.ml` and `<file>.mli`.
With previous version, it worked (See screenshot for parameters used) but it doesn't work anymore with 0.24.4.

Can you add a few lines in the README to explain how to add a new couple of extensions?

Thanks,

<img width="223" alt="screen shot 2017-12-14 at 07 55 36" src="https://user-images.githubusercontent.com/687155/33979350-3c7396aa-e0a4-11e7-8226-bc4609806b28.png">

**Comment by bguil** [comment]
I finally manage to make it work with the regular expression: `(.*)\.(ml|mli)$`.
Anyway, a few lines in README may be useful for other users.

**Comment by dschwen** [comment]
Yes, I agree. I'll reopen the issue to track the README update.

**Comment by dschwen** [comment]
Please reopen if you have further ideas on how to improve the README!
