### ISSUE TITLE
Error when opening atom

### ISSUE THREAD

**Issue by Kalabaza** [dschwen/switch-header-source#25]
[Enter steps to reproduce:]

1. Update packages to latest version.
2. Open atom an error window is displayed.

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [switch-header-source](https://github.com/dschwen/switch-header-source) package 0.26.0

### Stack Trace

Uncaught TypeError: atom.project.onDidChangeFiles is not a function

```
At /home/user/.atom/packages/switch-header-source/lib/switch-header-source.coffee:108

TypeError: atom.project.onDidChangeFiles is not a function
    at Object.startLoadPathsTask (/packages/switch-header-source/lib/switch-header-source.coffee:108:46)
    at /packages/switch-header-source/lib/switch-header-source.coffee:44:10
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:51.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
autocomplete-cmake 0.3.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.15 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.5 
language-cmake 0.3.0 
language-cpp14 0.6.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-ui-default 1.6.10 
python-indent 1.1.4 
script 3.17.3 
switch-header-source 0.26.0 
termination 0.6.1 
```

**Comment by dschwen** [comment]
Please update to the latest version (0.27.1) and see if that fixes your bug.

**Comment by dschwen** [comment]
You may need to update your atom as well (latest version may have a higher version requirement).

**Comment by Kalabaza** [comment]
I was not able to update to the latest version of the package with the version of atom that I had, so after updating atom and the package everything seems to work fine.

**Comment by dschwen** [comment]
Glad to hear that.
