### ISSUE TITLE
Prevent switching to build/header_symlinks directory

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/switch-header-source#28]
For some, but not all switches, `switch-header-source` finds the header in the `build/header_symlinks` directory, causing some pretty bad confusion if I'm not paying attention. There should be a way to prevent this, perhaps even simply in the regexp expression?

**Comment by dschwen** [comment]
@tophmatthews, I believe this is fixed in the latest release today. Let me know, otherwise we'll reopen.
