### ISSUE TITLE
Use Alt+O for Linux and Windows

### ISSUE THREAD

**Issue by jhasse** [dschwen/switch-header-source#3]
First: Great package, exactly what I was missing from Atom! Thanks!

I was wondering why you chose `Ctrl+Alt+S`. Sublime Text and Visual Assist X both use `Alt+O` for switching header/source.

What do you think about changing the shortcut for Linux and Windows? (I know I can easily change it myself, but using the default value feels better)

**Comment by dschwen** [comment]
Yeah, I could do Alt+O for Linux. I have simply not used Sublime or Visual Assist. I find the Ctrl+Alt+S shortcut convenient as it is one-hand accessible (thumb + index finger). The current Win/Linux shortcut is Ctrl+Alt+A (as the +S one did not work on Ubuntu).
