### ISSUE TITLE
src/materials/asdf/jkl.C switches to nonexistent include/materials/jkl.h

### ISSUE THREAD

**Issue by tophmatthews** [dschwen/switch-header-source#31]
If the source file is in multiple subfolders, it'll only go to the base subfolder to look for the header. This doesn't happen the other way around though (include/materials/asdf/jkl.h will switch to src/materials/asdf/jkl.C)

**Comment by dschwen** [comment]
@tophmatthews are you on the latest version of the plugin? Can you point me to a concrete example in one of the INL codes?

**Comment by tophmatthews** [comment]
Huh...this is really strange...

I checked other examples. In bison/src/materials/tensor_mechanics/*C, it wouldn't switch to anything. In bison/src/materials/tensor_mechanics/my_uncommitted_material.C would switch to an empty bison/src/materials/my_uncommitted_material.h

Then I went to verify the latest version of the plugin (0.29.0)
I saw language-moose had an update
I updated language-moose, which required an atom restart

...And now everything seems to work as normal? The version is still the same (0.29.0), but looks like the atom restart solved it?

I guess this issue is closed now, and the tried and true method works..."Have you tried unplugging it and plugging it back it?"

**Comment by dschwen** [comment]
@tophmatthews I think you did find a bug. Having to restart the editor is not a satisfactory solution. I ran into something similar I believe. I'll have to investigate this further, but it is hard to replicate. The plugin watches the filesystem for changes (delete, rename, new files) to incrementally update the switching index. This is much faster than the old method of crawling directories at every switch, but it seems to be more fragile.

**Comment by dschwen** [comment]
@tophmatthews I am about to release a new version in a moment that - I think - addresses your issue! Upon file deletion or moving the old name should be taken out of the list of files to switch to, but I am making a call to obtain the actual path of that file before I remove it (to disambiguate symlinked files). That call fails, however, if the deletion has progressed. I'm catching that error now so switching to nonexistent files should not happen anymore.
