### ISSUE TITLE
Fuzzy Finder changed startTask

### ISSUE THREAD

**Issue by robobenklein** [dschwen/switch-header-source#36]
https://github.com/dschwen/switch-header-source/blob/f41d2f32078ad776e8e7e9ca8d80ca22e27508cd/lib/switch-header-source.coffee#L124-L135

startTask is requiring a metricsReporter now, just ran into this problem trying to do the same thing. (Stealing the fuzzy finder stuff by manual require() joining)

In the end I just copied out the parts of fuzzy finder I needed and deleted the metrics related stuff: (hooray for MIT license!)

```
var fuzzyFinderMainModule = atom.packages.loadPackage('fuzzy-finder');
// copied most of fuzzy-finder into my own plugin:
var fuzzyFinderProjectView = require("./fuzzyfinder/project-view");

this.ff_ProjectView = new fuzzyFinderProjectView(
      fuzzyFinderMainModule.projectPaths
    );
```

**Comment by robobenklein** [comment]
Originally came up in https://github.com/atom/atom/issues/19163

**Comment by dschwen** [comment]
Added a hack on top the hack in d0e9bc539c613bd1c74de9ef3743e6f1f7258b25
