### ISSUE TITLE
Configurable file name extensions

### ISSUE THREAD

**Issue by kankaristo** [dschwen/switch-header-source#5]
Thanks for a great package, this should be core in Atom!

It would be nice to be able to configure the header/source file name extensions.

We use a custom class system in Lua, where the "header" file is `ClassName.lua` and the "definition" file is `ClassName_def.lua`.

Note that the extension doesn't actually change, so a regular expression would fit better (the extension needs to stay the same, because some tools rely on it to recognize it as a Lua file).

With configurable extensions, you could switch between *any* two related files, e.g. `.css` and `.sass`, etc.

**Comment by kankaristo** [comment]
I went ahead and wrote this. :)

Pull request coming soon!

**Comment by dschwen** [comment]
Manually merged and released as 0.19.0. Thanks!
