### ISSUE TITLE
switching between different directories

### ISSUE THREAD

**Issue by acampove** [dschwen/switch-header-source#9]
Hi,

I have my definitions (.cxx) in a ./src directory and my headers in an ./include directory, but I seem to be unable to switch from header to source using that package, is that possible? It seems to work only if they both are in the same directory.

Thanks.

**Comment by dschwen** [comment]
What is your header file extension? It should work by design, this is the main use for this plugin. I tested it with a ```./src/test.cxx``` and a ```./include/test.h``` file and it switched fine.

**Comment by acampove** [comment]
I have a directory structure as follows:

Test_Pkg
   include
        text.h
    src
        test.cxx

And it works like that. But if I rename as:

 include -> Test_Pkg and src->Root

 then it stops working. It seems that the problem is the change in the names of the include and source directories. In general for us (CERN) the include directory is called as the package, and the source directory is called Root.

**Comment by acampove** [comment]
I see you hardcoded the src and include names in https://github.com/dschwen/switch-header-source/blob/master/lib/switch-header-source.coffee. Is there a fast way of changing the "include" name to the name of the directory that contains "include"? I think I can change src myself to "Root".

**Comment by dschwen** [comment]
Oh, I see! Well, you could add symbolic links to have the directories
appear as src and include. I could also make this configurable. I can work
on that next week at the earliest though.

**Comment by acampove** [comment]
yes, i was thinking of symbolic links to.

Thanks.

**Comment by acampove** [comment]
Hi,

I think I got your package to do what I wanted, I just had to add a couple of things in the switch-header-source.coffee file.

If someone wants it it is liked below and has to replace the file in:
 $HOME/.atom/packages/switch-header-source/lib/

https://www.dropbox.com/s/ncfi8xw12y5607g/switch-header-source.coffee

**Comment by dschwen** [comment]
No drop box on my phone, but maybe you can do a pull request.
